# config.py

#fixed parameters 
TICK_DURATION = 2.0  # seconds
    #limit values
H_ENERGY = 30
R_ENERGY = 60
    #probs :
PREY_EAT_PROB = 0.8
PREY_REPRO_PROB = 0.5
PRED_HUNT_PROB = 0.8
PRED_REPRO_PROB = 0.5

#initial configuration parameters
INITIAL_PREDATORS = 0
INITIAL_PREYS = 0
INITIAL_GRASS = 1000
PREDATOR_INITIAL_ENERGY = 50
PREY_INITIAL_ENERGY = 50

#changes
PREDATOR_ENERGY_DECAY = 2
PREY_ENERGY_DECAY = 1
PREDATOR_EAT_GAIN = 30

MAX_PREDATORS = 50
MAX_PREYS = 200
MAX_GRASS = 1000

GRASS_GROWTH_PER_TICK = 10
DROUGHT_GRASS_FACTOR = 0.2

ENV_DISPLAY_QUEUE_MAXSIZE = 100

ENV_HOST = "127.0.0.1"
ENV_PORT = 50000

# pour la proie: 1 herbe = 1 énergie
PREY_MIN_EAT = 30
PREY_MAX_EAT_FACTOR = 1.3  # max_eat = int(R * factor)